### ISSUE TITLE
После редактирования категории она улетает в конец меню.

### ISSUE THREAD

**Issue by akorchaginn** [marker91/SimpleWebSite#12]
Изменить сортировку отдаваемых данных по категориям во вью.
Можно по дате создания, в идеале по Order, если пусто или равно, то по дате создания.

**Comment by marker91** [comment]
@akorchaginn 
Пример: 
order by Category.Order, Category.CreatedTime
норм?

**Comment by akorchaginn** [comment]
Вполне.

**Comment by marker91** [comment]
c5b4dca4b7030b801c1db374ea3f9b564aa63d44
