### ISSUE TITLE
Add into CategoryPagesViewModel CreatedTime attribute.

### ISSUE THREAD

**Issue by akorchaginn** [marker91/SimpleWebSite#14]
Add into CategoryPagesViewModel CreatedTime attribute.
![image](https://cloud.githubusercontent.com/assets/20842442/24018198/f4679c5c-0aa3-11e7-85d8-fec1e2ff5431.png)

**Comment by marker91** [comment]
fixed in f1038e66db902104a916f776df24f86150c17199
