### ISSUE TITLE
Вынести в параметры изменяемые значения.

### ISSUE THREAD

**Issue by akorchaginn** [marker91/SimpleWebSite#8]
Вынести в параметры изменяемые значения:

- Название организации,

- Логотип компании.

**Comment by marker91** [comment]
Создать таблицу Parameters c полями:
- Name(string - index)
- Value(string)

**Comment by marker91** [comment]
commit 403f8bdd7aea7031b7b831c9476abb6bdfd735af
commit a29ecd288f1de07dac31f19042e5599b2360b490
commit aa4b3f54bef31a51b6647d66f039a174b27e1472

**Comment by marker91** [comment]
@akorchaginn Нужно ли реализовывать контроллер для редактирования параметров?

**Comment by marker91** [comment]
commit a2303efec3ea6ad983dd4442ad28efdfe79b108f impl settings controller and crud operation view
